DROP TABLE IF EXISTS manga;

CREATE TABLE manga (
	id INT(4) NOT NULL AUTO_INCREMENT,
	name VARCHAR(255),
	kana VARCHAR(255),
	num INT(4),
	regdate DATETIME,
	PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET = utf8